baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "JH"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "JH"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "light"

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "JH" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hello, I am"
    title: "Jihyuk"
    subtitle: "I am a software developer"
    content: "A passionate software developer, I believe that every experience is an opportunity to learn."
    # Todo: replace image
    image: /images/hero.svg
    bottomImage:
      enable: true
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/jihyuky
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/jihyuk-yoon/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
        I am a student at the University of Toronto studying computer science. I am passionate about software development, and I constantly learn from others through working at a start-up, team projects, and other community involvements.
        
        I love traveling, working out, swimming at the lake, and cooking. 

        Check out the blog section to learn more about my life, including my military experience, my family and friends, and my workout routines!

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "React"
        - "HTML5"
        - "JavaScript"
        - "Python"
        - "Java"
        - "Assembly"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Developer"
        company: "Ensighter Group"
        # companyUrl: ""
        date: "Dec 2023 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "I have recently took part in the Laureate Club, which is part of the start-up Ensighter Group. Here, I work backend and frontend for the company website."





  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Computer Science Specialist"
        school:
          name: "University of Toronto"
          url: "https://www.utoronto.ca/"
        date: "2020 - Expected May 2026"
        GPA: "4.0 / 4.0"
        content: |-
              Taking courses related to software design, theory of computation, computer organization, multivariable calculus, statistics and data analysis, and data structures. 
              General Council member of the Computer Science Student Union, and taking part in UofT Hackathons.


  # # Achievements
  # achievements:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #       image: /images/achievment.jpg
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #       image: /images/achievment.jpg
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #       image: /images/achievment.jpg
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Benson
        content: Java application for doctors and patients to get connected by the patient talking to an AI trained bot and the system recommending the patient doctors.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://drive.google.com/file/d/15e1RN2wjtsaNpl23oyX-mzIISezhSCVC/view?usp=sharing
        badges:
          - "Java"
          - "Dialogflow"
          - "MongoDB"
        links:
          - icon: fab fa-github
            url: https://github.com/Accusamus2065/CSC207-Project


      - title: Chat App
        content: An Android application built for chatting with your friends by using Firebase Firestore.
        image: /images/projects/converter.png
        featured:
          name: How it looks
          link: https://drive.google.com/file/d/1-BPAuADEbbgotEY6djKvpgTUdy4FKOkS/view?usp=sharing
        badges:
          - "Java"
          - "XML"
          - "Firebase"
        links:
          - icon: fab fa-github
            url: https://github.com/jihyuky/Messages

      - title: Board
        content: A clean and simple site for posting one's opinion on various things. Multi-purpose site, as it could be used for brainstorming, leaving notes for each other, or leaving memos for yourself.
        image: /images/projects/board.png
        featured:
          name: How it looks
          link: https://drive.google.com/file/d/1S8M8oq0cDohxWhPBAmkvYRpqn-j6EJP4/view?usp=sharing
        badges:
          - "Javascript"
          - "React"
        links:
          - icon: fab fa-github
            url: https://github.com/jihyuky/Board

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Feel free to email me for any further questions!
    email: jihyuky@gmail.com
    btnName: Mail me
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: mbjnjayr # Take it from your form's endpoint, like 'https://formspree.io/f/mbjnjayr'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
